/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FavoritesLazyImport = createFileRoute('/favorites')()
const CartLazyImport = createFileRoute('/cart')()
const IndexLazyImport = createFileRoute('/')()
const PizzaIdLazyImport = createFileRoute('/pizza/$id')()

// Create/Update Routes

const FavoritesLazyRoute = FavoritesLazyImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/favorites.lazy').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cart.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PizzaIdLazyRoute = PizzaIdLazyImport.update({
  id: '/pizza/$id',
  path: '/pizza/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pizza/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyImport
      parentRoute: typeof rootRoute
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesLazyImport
      parentRoute: typeof rootRoute
    }
    '/pizza/$id': {
      id: '/pizza/$id'
      path: '/pizza/$id'
      fullPath: '/pizza/$id'
      preLoaderRoute: typeof PizzaIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/pizza/$id': typeof PizzaIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cart': typeof CartLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/pizza/$id': typeof PizzaIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cart': typeof CartLazyRoute
  '/favorites': typeof FavoritesLazyRoute
  '/pizza/$id': typeof PizzaIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart' | '/favorites' | '/pizza/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/favorites' | '/pizza/$id'
  id: '__root__' | '/' | '/cart' | '/favorites' | '/pizza/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CartLazyRoute: typeof CartLazyRoute
  FavoritesLazyRoute: typeof FavoritesLazyRoute
  PizzaIdLazyRoute: typeof PizzaIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CartLazyRoute: CartLazyRoute,
  FavoritesLazyRoute: FavoritesLazyRoute,
  PizzaIdLazyRoute: PizzaIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cart",
        "/favorites",
        "/pizza/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/cart": {
      "filePath": "cart.lazy.jsx"
    },
    "/favorites": {
      "filePath": "favorites.lazy.jsx"
    },
    "/pizza/$id": {
      "filePath": "pizza/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
