/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PizzaLazyImport = createFileRoute('/pizza')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PizzaLazyRoute = PizzaLazyImport.update({
  id: '/pizza',
  path: '/pizza',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pizza.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pizza': {
      id: '/pizza'
      path: '/pizza'
      fullPath: '/pizza'
      preLoaderRoute: typeof PizzaLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/pizza': typeof PizzaLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/pizza': typeof PizzaLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/pizza': typeof PizzaLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pizza'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pizza'
  id: '__root__' | '/' | '/pizza'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  PizzaLazyRoute: typeof PizzaLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  PizzaLazyRoute: PizzaLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/pizza"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/pizza": {
      "filePath": "pizza.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
